# Generated by Django 2.1.7 on 2019-02-20 16:31

from django.db import migrations, models
import django.db.models.deletion
import sheets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sheets.models.get_sheet_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='SheetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language')),
            ],
        ),
        migrations.CreateModel(
            name='SuperColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
                ('super_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.SuperColumn')),
            ],
        ),
        migrations.CreateModel(
            name='SuperSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sheets.ColumnName')),
                ('super_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.SuperColumn')),
            ],
        ),
        migrations.CreateModel(
            name='TableRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.TableColumn')),
            ],
            options={
                'ordering': ['column', 'start_year', 'end_year'],
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sheets.SheetName'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='supersheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheets.SuperSheet'),
        ),
        migrations.AddField(
            model_name='columnname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='tablerows',
            unique_together={('column', 'start_year')},
        ),
    ]
