# Generated by Django 2.1.7 on 2019-02-24 14:04

from django.db import migrations, models
import django.db.models.deletion
import sheets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'ordering': ['feature', 'start_year', 'end_year'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_loc', models.FileField(upload_to=sheets.models.get_sheet_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SheetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Type')),
            ],
        ),
        migrations.CreateModel(
            name='TypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Type')),
            ],
        ),
        migrations.AddField(
            model_name='featurename',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language'),
        ),
        migrations.AddField(
            model_name='feature',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
        migrations.AddField(
            model_name='cell',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
        ),
        migrations.AddField(
            model_name='cell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Type'),
        ),
        migrations.AddField(
            model_name='categoryname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Language'),
        ),
    ]
