# Generated by Django 2.1.7 on 2019-02-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supercolumn',
            old_name='super_column',
            new_name='parent_column',
        ),
    ]
