# Generated by Django 2.1.7 on 2019-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20190225_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.FloatField(),
        ),
    ]
