# Generated by Django 2.1.7 on 2019-02-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20190220_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tablecolumn',
            name='column_name',
        ),
        migrations.AddField(
            model_name='columnname',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.TableColumn'),
        ),
        migrations.AddField(
            model_name='sheetname',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='tablerows',
            unique_together=set(),
        ),
    ]
