# Generated by Django 2.1.7 on 2019-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20190225_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurename',
            name='start_year',
            field=models.IntegerField(default=2011),
            preserve_default=False,
        ),
    ]
