# Generated by Django 2.1.7 on 2019-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_featurename_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurename',
            name='start_year',
        ),
        migrations.AddField(
            model_name='feature',
            name='start_year',
            field=models.IntegerField(default=2011),
            preserve_default=False,
        ),
    ]
