# Generated by Django 2.1.7 on 2019-02-28 10:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20190225_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Type')),
            ],
        ),
    ]
