# Generated by Django 2.1.7 on 2019-02-28 13:55

from django.db import migrations, models
import sheets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_featurerow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file_loc',
            field=models.FileField(max_length=1000, upload_to=sheets.models.get_sheet_upload_path),
        ),
    ]
