# Generated by Django 2.1.7 on 2019-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_auto_20190228_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurename',
            name='is_property',
            field=models.BooleanField(default=False),
        ),
    ]
