# Generated by Django 2.1.7 on 2019-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_featurename_is_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurename',
            name='is_property',
        ),
        migrations.AddField(
            model_name='feature',
            name='is_property',
            field=models.BooleanField(default=False),
        ),
    ]
