# Generated by Django 2.1.7 on 2019-03-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_auto_20190302_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('parent_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Entity')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='start_year',
        ),
        migrations.AddField(
            model_name='entity',
            name='parent_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
    ]
