# Generated by Django 2.1.7 on 2019-03-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_auto_20190302_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='start_year',
        ),
        migrations.AddField(
            model_name='featurerow',
            name='start_year',
            field=models.IntegerField(default=2011),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
        ),
    ]
