# Generated by Django 2.1.7 on 2019-03-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_auto_20190302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerow',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sheets.Entity'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='featurerow',
            unique_together={('feature', 'entity')},
        ),
    ]
