# Generated by Django 2.1.7 on 2019-03-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_auto_20190302_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerow',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheets.Entity'),
        ),
        migrations.AlterField(
            model_name='featurerow',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
        ),
        migrations.AlterField(
            model_name='featurerow',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheets.Type'),
        ),
    ]
