# Generated by Django 2.1.7 on 2019-03-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_auto_20190302_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerow',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sheets.Entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurerow',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
            preserve_default=False,
        ),
    ]
