# Generated by Django 2.1.7 on 2019-03-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_auto_20190302_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerow',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Entity'),
        ),
        migrations.AlterField(
            model_name='featurerow',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='featurerow',
            unique_together={('feature', 'entity', 'type')},
        ),
    ]
