# Generated by Django 2.1.7 on 2019-03-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_auto_20190302_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerow',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Feature'),
        ),
    ]
