# Generated by Django 2.1.7 on 2019-03-03 09:49

from django.db import migrations, models
import sheets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_auto_20190302_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='meta_file_loc',
            field=models.FileField(default='hello', max_length=10000, upload_to=sheets.models.get_sheet_upload_path),
            preserve_default=False,
        ),
    ]
